version: '3.7'

networks:
  4i0n4s:

services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    networks:
      4i0n4s:
    container_name: "mosquitto"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart:
      "always"

  forwarder:
    build: ./forwarder
    networks:
      4i0n4s:
    environment:
      - MQTT_BROKER=mqtt://mosquitto
    depends_on:
      - mosquitto
    restart:
      "always"

  publisher:
    build: ./publisher
    networks:
      4i0n4s:
    restart:
      "always"

  backend:
    build: ./backend
    networks:
      4i0n4s:
    container_name: "backend"
    restart:
      "always"
    ports:
      - "1337:1337"

volumes:
  mosquitto_data:
  mosquitto_log:
