version: '3.7'

networks:
  4i0n4s:

services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    networks:
      4i0n4s:
    container_name: "mosquitto"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  mock_publisher:
    build: ./mockPublisher
    networks:
      4i0n4s:

  logger:
    build: ./logger
    networks:
      4i0n4s:
    environment:
      - MQTT_BROKER=mosquitto

volumes:
  mosquitto_data:
  mosquitto_log:
