version: '3.7'

services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  logger:
    build: ./logger
    environment:
      - MQTT_BROKER=mosquitto

volumes:
  mosquitto_data:
  mosquitto_log:
